name: Commit Message Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event.pull_request.user.login != 'dependabot[bot]'

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check PR commits
        if: github.event_name == 'pull_request'
        run: |
          util/check-commit-messages \
            ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}

      - name: Check HEAD commit
        if: github.event_name == 'workflow_dispatch'
        run: util/check-commit-messages HEAD~1..HEAD
