name: Forbid Merge Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  forbid-merge-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Run Forbid Merge Commits Action
        uses: motlin/forbid-merge-commits-action@v1.0.7
        with:
          fail-on-merge-commits: true
